import { z } from 'zod';

export const ROLES_HIERARCHY = [
  'STUDENT',
  'GRADER',
  'TA',
  'PROFESSOR',
  'HEAD_OF_COURSE',
  'SCHOOL_MANAGER',
  'UNIV_ADMIN',
  'SUPER_ADMIN',
] as const;

export type RoleHierarchy = (typeof ROLES_HIERARCHY)[number];

export const PermissionAction = {
  SUBMIT_HOMEWORK: 'SUBMIT_HOMEWORK',
  VIEW_OWN_GRADE: 'VIEW_OWN_GRADE',
  ASK_AI_FOLLOWUP: 'ASK_AI_FOLLOWUP',
  REVIEW_OVERRIDE_GRADE: 'REVIEW_OVERRIDE_GRADE',
  CREATE_ASSIGNMENT: 'CREATE_ASSIGNMENT',
  TOGGLE_AUTO_RELEASE: 'TOGGLE_AUTO_RELEASE',
  DEFINE_PREREQUISITES: 'DEFINE_PREREQUISITES',
  REQUEST_RUBRIC_SUGGESTIONS: 'REQUEST_RUBRIC_SUGGESTIONS',
  SET_RESUBMISSION_COUNT: 'SET_RESUBMISSION_COUNT',
  SET_RELEASE_POLICY: 'SET_RELEASE_POLICY',
  SET_SYSTEM_RESUBMISSION_CAP: 'SET_SYSTEM_RESUBMISSION_CAP',
  VIEW_OWN_COURSE_BILLING: 'VIEW_OWN_COURSE_BILLING',
  VIEW_SCHOOL_BILLING: 'VIEW_SCHOOL_BILLING',
  VIEW_UNIVERSITY_BILLING: 'VIEW_UNIVERSITY_BILLING',
  VIEW_PLATFORM_BILLING: 'VIEW_PLATFORM_BILLING',
  CREATE_SCHOOL: 'CREATE_SCHOOL',
  ASSIGN_HEAD_OF_COURSE: 'ASSIGN_HEAD_OF_COURSE',
  IMPERSONATE_USER: 'IMPERSONATE_USER',
  CHANGE_FEATURE_FLAGS: 'CHANGE_FEATURE_FLAGS',
  MANAGE_UNIVERSITY: 'MANAGE_UNIVERSITY',
  MANAGE_COURSE: 'MANAGE_COURSE',
  MANAGE_SCHOOL: 'MANAGE_SCHOOL',
  VIEW_SUBMISSIONS: 'VIEW_SUBMISSIONS',
  UPLOAD_MATERIALS: 'UPLOAD_MATERIALS',
  VIEW_ANALYTICS: 'VIEW_ANALYTICS',
  EXPORT_GRADEBOOK: 'EXPORT_GRADEBOOK',
} as const;

export type PermissionAction = (typeof PermissionAction)[keyof typeof PermissionAction];

export const RolePermissionsSchema = z.object({
  role: z.string(),
  actions: z.array(z.string()),
});
